<?php

namespace Tests\Feature;

use App\Repositories\UserRepository;
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Testing\TestResponse;
use Tests\TestCase;

class ApIItemControllerDeleteTest extends TestCase
{
    protected Authenticatable|Model $user;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = (new UserRepository())->getById(1);
    }
    public function testDeleteApi() {
        $response = $this->deleteRequestToRouteDelete('api/delete/1');
        $response->assertStatus(200);
        $response->assertJsonPath('message',"Success, item deleted!");
        $response->assertJsonPath('success',true);
    }
    public function testDeleteApiItemNotExist() {
        $response = $this->deleteRequestToRouteDelete('api/delete/10');
        $response->assertStatus(500);
        $response->assertJsonPath('message',"Item doesnt exist");
        $response->assertJsonPath('success',false);
    }

    private function deleteRequestToRouteDelete($uri): TestResponse {
        return $this->actingAs($this->user)
            ->withSession(['banned' => false])
            ->delete($uri);
    }

}
