<?php

namespace Tests\Feature;

use App\Repositories\UserRepository;
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Tests\TestCase;

class ItemControllerTest extends TestCase
{
    protected Authenticatable|Model $user;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = (new UserRepository())->getById(1);
    }
    public function testHomePage(): void
    {
        $response = $this->get('/');
        $response->assertStatus(200);
    }

    public function testAccessTokenApi() {
        $response = $this->post('api/personal-access-tokens', ['email'=>'artem@mail.ru', 'password'=>'qweasdzxc']);
        $response->assertStatus(200);
        $response->assertJsonPath('message','Success');
    }
    public function testShowAllApi() {
        $response = $this->actingAs($this->user)
            ->withSession(['banned' => false])
            ->get('api/show-all');
        $content = json_decode($response->getContent(), true);
        $response->assertStatus(200);
        $response->assertJsonPath('message',null);
        $response->assertJsonPath('success',true);
        self::assertCount(2, $content['data']);
    }
    public function testShowApi() {
        $response = $this->actingAs($this->user)
            ->withSession(['banned' => false])
            ->get('api/show/1');
        $content = json_decode($response->getContent(), true);
        $response->assertStatus(200);
        $response->assertJsonPath('message',null);
        $response->assertJsonPath('success',true);
        self::assertEquals("test", $content['data']['name']);
        self::assertEquals("1", $content['data']['key']);
    }
    public function testShowApiError() {
        $response = $this->actingAs($this->user)
            ->withSession(['banned' => false])
            ->get('api/show/10');
        $response->assertStatus(500);
        $response->assertJsonPath('message',"Item doesnt exist");
        $response->assertJsonPath('success',false);
    }
    public function testUpdateApi() {
        $response = $this->actingAs($this->user)
            ->withSession(['banned' => false])
            ->put('api/update/1', ['name'=>'update test', 'key'=>'update test']);
        $content = json_decode($response->getContent(), true);
        $response->assertStatus(200);
        $response->assertJsonPath('message',"Success, item updated!");
        $response->assertJsonPath('success',true);
        self::assertEquals("update test", $content['data']['name']);
        self::assertEquals("update test", $content['data']['key']);
    }
    public function testUpdateApiErrorKey() {
        $response = $this->actingAs($this->user)
            ->withSession(['banned' => false])
            ->put('api/update/3', ['name'=>'update test']);
        $response->assertStatus(500);
        $response->assertJsonPath('success',false);
        $response->assertJsonPath('message',"Validation error");
    }
    public function testUpdateApiItemNotExist() {
        $response = $this->actingAs($this->user)
            ->withSession(['banned' => false])
            ->put('api/update/10', ['name'=>'update test', 'key'=>"123"]);
        $response->assertStatus(500);
        $response->assertJsonPath('message',"Item doesnt exist");
        $response->assertJsonPath('success',false);
    }
    public function testStoreApi() {
        $response = $this->actingAs($this->user)
            ->withSession(['banned' => false])
            ->post('api/store', ['name'=>'store test', 'key'=>'store test']);
        $content = json_decode($response->getContent(), true);
        $response->assertStatus(200);
        $response->assertJsonPath('message',"Success, item stored!");
        $response->assertJsonPath('success',true);
        self::assertEquals("store test", $content['data']['name']);
        self::assertEquals("store test", $content['data']['key']);
    }
    public function testItemRequestValidationError() {
        $response = $this->actingAs($this->user)
            ->withSession(['banned' => false])
            ->post('api/store', ['name'=>'store test']);
        $response->assertStatus(500);
        $response->assertJsonPath('success',false);
        $response->assertJsonPath('message',"Validation error");
    }
    public function testDeleteApi() {
        $response = $this->actingAs($this->user)
            ->withSession(['banned' => false])
            ->delete('api/delete/1');
        $response->assertStatus(200);
        $response->assertJsonPath('message',"Success, item deleted!");
        $response->assertJsonPath('success',true);
    }
    public function testDeleteApiItemNotExist() {
        $response = $this->actingAs($this->user)
            ->withSession(['banned' => false])
            ->delete('api/delete/10');
        $response->assertStatus(500);
        $response->assertJsonPath('message',"Item doesnt exist");
        $response->assertJsonPath('success',false);
    }
}
