<?php

namespace Tests\Unit;

use App\Models\Item;
use App\Models\User;
use App\Repositories\ItemRepository;
use App\Repositories\UserRepository;
use App\Services\ItemService;
use Database\Factories\ItemFactory;
use Tests\TestCase;

class ItemServiceTest extends TestCase
{
    private ItemService $service;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->service = new ItemService(new ItemRepository());
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */

    public function testCreateUser() {
        $this->assertDatabaseHas('users', ['name' => 'artem']);
    }
    public function testCreateItem() {
        $this->assertDatabaseHas('items', ['name' => 'test']);
    }
    public function testShowAll(){
        $result = $this->service->showAll();
        $this->assertEquals(2, count($result));
    }
}
